### PR TITLE
Update resolution 1x for ipad in appicon_action.rb

### PR DESCRIPTION
**Pull request by biolinh**
Thank your for your plugin you write.
I use it effectively then i want to generate appicon for iPad with dimension '83.5x83.5'.
Please helps me merge it into code. Thanks

### CODE REVIEW

**Review by KrauseFx — APPROVED** [review]

**Comment by KrauseFx** [comment]
Thanks for the PR. Do you need a new release for this too?

**Comment by biolinh** [comment]
@KrauseFx Thank for your response. I really appreciate for its appear in the next release. Please notify me, I will update fastlane into latest version.

**Comment by KrauseFx** [comment]
Done  🚀

**Comment by biolinh** [comment]
Great job you do. Thank you.

**Comment by biolinh** [comment]
@KrauseFx: Reverting code is ok for me. :(. Thank you.

**Pull request merged**
