### PR TITLE
Rearrangement of android_appicon action parameters

### PR DESCRIPTION
**Pull request by krzysztof-miemiec**
# Rearrangement of `android_appicon` action parameters
## Description
**This PR contains breaking changes for `android_appicon` action.**

Besides fixing the issue https://github.com/KrauseFx/fastlane-plugin-appicon/issues/30, I decided to change parameters to something that seems more reasonable to me. Instead of `devices` parameter I used `icon_types`, which provide icon sizes for the type (launcher, notification) instead of device (phone, tablet).

## Changes
* Added sample notification icon to `spec/` and mentioned it in `README.md`.
* Added `gems/` to `.gitignore`.
* Changed `appicon_devices` to `appicon_icon_types`, merged `tablet` and `phone` into `launcher` type (as most Android devices are xxhdpi or xxxhdpi nowadays).
* Added `notification` type that can be used to generate notification icons, which replaces `notification_icons` and additional parameters.
* Fixed potential issue mentioned in https://github.com/KrauseFx/fastlane-plugin-appicon/issues/30 by setting default, empty `appicon_custom_sizes` parameter.

### CODE REVIEW

**Comment by felipeplets** [comment]
@krzysztof-miemiec your PR seems good to me.

**Review by felipeplets — APPROVED** [review]

**Comment by felipeplets** [comment]
@KrauseFx and @joshdholtz can you check it so we can release version 0.12?

**Comment by felipeplets** [comment]
@KrauseFx can you please check it? From my tests it's ok to go for 0.12.0.

**Comment by KrauseFx** [comment]
Thanks, just pushed a new release 👍

**Pull request merged**
