### PR TITLE
added support for launch images for android

### LINKED ISSUE #53: add support for launch images
I think we can add support for launch images for android as well. I am going to create a PR for this.

### PR DESCRIPTION
**Pull request by RishabhTayal**
fixes: #53

### CODE REVIEW

**Comment by josh-m-sharpe** [comment]
Probably fixes #49 too

**Comment by josh-m-sharpe** [comment]
@RishabhTayal Couple of thoughts here:

1) There's no README update
2) From the code it doesn't look like it supports both portrait and landscape images
3) "launch_image" seems too similar to "launcher" - Why not use "splash" instead?

**Comment by josh-m-sharpe** [comment]
Forcibly resizing the image is probably not a good idea either since the final sizes are all different ratios.  You probably want to resize the image to a square and then trim in the sides - that would at least keep the aspect ratio of the original image correct.

**Comment by josh-m-sharpe** [comment]
Yea - if you remove the `!` here: https://github.com/KrauseFx/fastlane-plugin-appicon/pull/54/files#diff-d29e0527a6452a0d57b299118a56018fR64 then aspect ratio is preserved.  I suspect most users would prefer it that way.

**Comment by ssilverr** [comment]
Any news on this?

**Comment by joshdholtz** [comment]
Closed due to #54

**Comment by ssilverr** [comment]
@joshdholtz this is #54. Did you mean #56 ?

**Comment by joshdholtz** [comment]
lol I did 😝

**Pull request closed without merging**
