### PR TITLE
Add support for Xcode 9 embedded App Store icon

### PR DESCRIPTION
**Pull request by PatrickNLT**
This adds support for the 1024x1024 App Store icon that is required when submitting a build to iTunes Connect using Xcode 9.

### CODE REVIEW

**Comment by KrauseFx** [comment]
Awesome, thanks. Quick question: does the new iTC with Xcode 9 require the app icon to be in the asset catalog, or just being uploaded to iTC?

**Comment by PatrickNLT** [comment]
It needs to be in the asset catalog. Otherwise, this is the message you get:

> Missing Marketing Icon - iOS Apps must include a 1024x1024px Marketing Icon in PNG format. Apps that do not include the Marketing Icon cannot be submitted for App Review or Beta App Review.

**Comment by felipeplets** [comment]
@PatrickNLT since it is the standard from now on, wouldn't it be better to just add the resolution to both iOS and ipad sets instead of creating a new one?

**Comment by PatrickNLT** [comment]
`ios-marketing` is actually considered by Xcode as a new idiom and not a new resolution. That's why it needs to be a separate thing (unless I'm missing something).

**Comment by felipeplets** [comment]
@PatrickNLT sorry I missed that, you are right. In my opinion the PR is good to go.

**Review by KrauseFx — APPROVED** [review]
Awesome, thanks 👍

**Pull request merged**
