### PR TITLE
generates rounded images

### LINKED ISSUE #42: Adaptive icon support?
Thank you for such a fantastic plugin! Runs great for me on iOS and Android. I was wondering if there were any plans for [android adaptive icons?](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive) Android SDK 26+ allows for these types of icons. Users can now choose their icon style (circle or square), and the icons generated by this plugin result in a small square icon within a white circle if the user has their icons set as circular (see photo).

screen shot 2018-07-17 at 5 59 56 pm

### PR DESCRIPTION
**Pull request by RishabhTayal**
fixes: #42

### CODE REVIEW

**Comment by GazzaHazza** [comment]
anything happening with this?

**Comment by mortenholmgaard** [comment]
@joshdholtz Please have a look at this pull request.

**Review by joshdholtz — APPROVED** [review]
@RishabhTayal Thanks for making this PR years ago 😊 Merging and releasing!

**Comment by josh-m-sharpe** [comment]
Shouldn't there be some update to the README to document this?

**Comment by dandre-hound** [comment]
@RishabhTayal and @josh-m-sharpe I'm not actually seeing ic_launcher_foreground.png files generated after setting generated_rounded to true and supplying "launcher" for appicon_icon_types. I see the line that generates these files [here](https://github.com/josh-m-sharpe/fastlane-plugin-appicon/blob/master/lib/fastlane/plugin/appicon/actions/android_appicon_action.rb#L89). Is there something I'm missing here? Or does the rounded icon that's generated already contain an alpha channel or something?

**Pull request merged**
